
project_id = "ikbnplncntfftvghvrgv"

[functions.create-subscription]
verify_jwt = true

[functions.create-gift-payment]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.stripe-webhook-handler]
verify_jwt = false
